server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://i8a605.p.ssafy.io:3306/unnamed?useUnicode=true&serverTimezone=Asia/Seoul
    username: testuser
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
#      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true

# S3
cloud:
  aws:
    credentials:
      accessKey: AKIAQUIHCELPJ3PJXH55
      secretKey: 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
    s3:
      bucket: s3ffmpegtest
    region:
      static: ap-northeast-2

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
